In [5]:
import pandas as pd
import numpy as np

In [6]:
df=pd.DataFrame({
     "Gender": ["Male", "Female", "Male", None],
    "Education": ["Graduate", "Not Graduate", "Graduate", "Graduate"],
    "LoanAmount": [100, 150, np.nan, 200],
    "Loan_Status": ["Y", "N", "Y", "N"]})
df

   Gender     Education  LoanAmount Loan_Status
0    Male      Graduate       100.0           Y
1  Female  Not Graduate       150.0           N
2    Male      Graduate         NaN           Y
3    None      Graduate       200.0           N

In [4]:
#sum of null values based on the columns
df.isnull().sum()

Gender         1
Education      0
LoanAmount     1
Loan_Status    0
dtype: int64

In [7]:
#fillig missing values 
df.ffill(inplace=True)
df.bfill(inplace=True)
df

   Gender     Education  LoanAmount Loan_Status
0    Male      Graduate       100.0           Y
1  Female  Not Graduate       150.0           N
2    Male      Graduate       150.0           Y
3    Male      Graduate       200.0           N

In [12]:
#ML models cannot read text like "Male","Graduate"
df1=pd.get_dummies(
    df,columns=[
        "Gender","Education","Loan_Status"])
df1=df1.astype(int)
df1

,LoanAmount,Gender_Female,Gender_Male,Education_Graduate,Education_Not Graduate,Loan_Status_N,Loan_Status_Y
0,100,0,1,1,0,0,1
1,150,1,0,0,1,1,0
2,150,0,1,1,0,0,1
3,200,0,1,1,0,1,0

In [24]:
#to drop unnecessary tables
df1.drop(["Gender_Male", "Education_Not Graduate", "Loan_Status_Y"],
         axis=1,
         inplace=True,
         errors="ignore")
print(df1.columns)

Index(['LoanAmount'], dtype='object')

In [9]:
df = pd.read_csv(r"C:\Users\jacob\Downloads\loan_data_set_lyst1728376986423 (1).csv")
df.ffill(inplace=True)
df.bfill(inplace=True)
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,128.0,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [10]:
df1=pd.get_dummies(df,columns=[
     "Gender", "Married", "Dependents",
        "Education", "Self_Employed",
        "Property_Area", "Loan_Status"
    ]
                  )
df1

,Loan_ID,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Gender_Female,Gender_Male,Married_No,Married_Yes,...,Dependents_3+,Education_Graduate,Education_Not Graduate,Self_Employed_No,Self_Employed_Yes,Property_Area_Rural,Property_Area_Semiurban,Property_Area_Urban,Loan_Status_N,Loan_Status_Y
0,LP001002,5849,0.0,128.0,360.0,1.0,False,True,True,False,...,False,True,False,True,False,False,False,True,False,True
1,LP001003,4583,1508.0,128.0,360.0,1.0,False,True,False,True,...,False,True,False,True,False,True,False,False,True,False
2,LP001005,3000,0.0,66.0,360.0,1.0,False,True,False,True,...,False,True,False,False,True,False,False,True,False,True
3,LP001006,2583,2358.0,120.0,360.0,1.0,False,True,False,True,...,False,False,True,True,False,False,False,True,False,True
4,LP001008,6000,0.0,141.0,360.0,1.0,False,True,True,False,...,False,True,False,True,False,False,False,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,2900,0.0,71.0,360.0,1.0,True,False,True,False,...,False,True,False,True,False,True,False,False,False,True
610,LP002979,4106,0.0,40.0,180.0,1.0,False,True,False,True,...,True,True,False,True,False,True,False,False,False,True
611,LP002983,8072,240.0,253.0,360.0,1.0,False,True,False,True,...,False,True,False,True,False,False,False,True,False,True
612,LP002984,7583,0.0,187.0,360.0,1.0,False,True,False,True,...,False,True,False,True,False,False,False,True,False,True
613,LP002990,4583,0.0,133.0,360.0,0.0,True,False,True,False,...,False,True,False,False,True,False,True,False,True,False

In [11]:
df1.drop("Gender_Female", axis=1, inplace=True)
df1.drop("Education_Graduate", axis=1, inplace=True)
df1.drop("Loan_Status_N", axis=1, inplace=True)
df1

,Loan_ID,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Gender_Male,Married_No,Married_Yes,Dependents_0,Dependents_1,Dependents_2,Dependents_3+,Education_Not Graduate,Self_Employed_No,Self_Employed_Yes,Property_Area_Rural,Property_Area_Semiurban,Property_Area_Urban,Loan_Status_Y
0,LP001002,5849,0.0,128.0,360.0,1.0,True,True,False,True,False,False,False,False,True,False,False,False,True,True
1,LP001003,4583,1508.0,128.0,360.0,1.0,True,False,True,False,True,False,False,False,True,False,True,False,False,False
2,LP001005,3000,0.0,66.0,360.0,1.0,True,False,True,True,False,False,False,False,False,True,False,False,True,True
3,LP001006,2583,2358.0,120.0,360.0,1.0,True,False,True,True,False,False,False,True,True,False,False,False,True,True
4,LP001008,6000,0.0,141.0,360.0,1.0,True,True,False,True,False,False,False,False,True,False,False,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,2900,0.0,71.0,360.0,1.0,False,True,False,True,False,False,False,False,True,False,True,False,False,True
610,LP002979,4106,0.0,40.0,180.0,1.0,True,False,True,False,False,False,True,False,True,False,True,False,False,True
611,LP002983,8072,240.0,253.0,360.0,1.0,True,False,True,False,True,False,False,False,True,False,False,False,True,True
612,LP002984,7583,0.0,187.0,360.0,1.0,True,False,True,False,False,True,False,False,True,False,False,False,True,True
613,LP002990,4583,0.0,133.0,360.0,0.0,False,True,False,True,False,False,False,False,False,True,False,True,False,False

In [19]:
#iloc=index based selection
#: selectall
x=df1.iloc[:, :-1]#Data used to learn (features)
y=df1.iloc[:,-1]#Data used to learn (features)
print(x)
print(y)

      Loan_ID  ApplicantIncome  CoapplicantIncome  LoanAmount  \
0    LP001002             5849                0.0       128.0
1    LP001003             4583             1508.0       128.0
2    LP001005             3000                0.0        66.0
3    LP001006             2583             2358.0       120.0
4    LP001008             6000                0.0       141.0
..        ...              ...                ...         ...
609  LP002978             2900                0.0        71.0
610  LP002979             4106                0.0        40.0
611  LP002983             8072              240.0       253.0
612  LP002984             7583                0.0       187.0
613  LP002990             4583                0.0       133.0

     Loan_Amount_Term  Credit_History  Gender_Male  Married_No  Married_Yes  \
0               360.0             1.0         True        True        False
1               360.0             1.0         True       False         True
2               360.0             1.0         True       False         True
3               360.0             1.0         True       False         True
4               360.0             1.0         True        True        False
..                ...             ...          ...         ...          ...
609             360.0             1.0        False        True        False
610             180.0             1.0         True       False         True
611             360.0             1.0         True       False         True
612             360.0             1.0         True       False         True
613             360.0             0.0        False        True        False

     Dependents_0  Dependents_1  Dependents_2  Dependents_3+  \
0            True         False         False          False
1           False          True         False          False
2            True         False         False          False
3            True         False         False          False
4            True         False         False          False
..            ...           ...           ...            ...
609          True         False         False          False
610         False         False         False           True
611         False          True         False          False
612         False         False          True          False
613          True         False         False          False

     Education_Not Graduate  Self_Employed_No  Self_Employed_Yes  \
0                     False              True              False
1                     False              True              False
2                     False             False               True
3                      True              True              False
4                     False              True              False
..                      ...               ...                ...
609                   False              True              False
610                   False              True              False
611                   False              True              False
612                   False              True              False
613                   False             False               True

     Property_Area_Rural  Property_Area_Semiurban  Property_Area_Urban
0                  False                    False                 True
1                   True                    False                False
2                  False                    False                 True
3                  False                    False                 True
4                  False                    False                 True
..                   ...                      ...                  ...
609                 True                    False                False
610                 True                    False                False
611                False                    False                 True
612                False                    False                 True
613                False                     True                False

[614 rows x 19 columns]
0       True
1      False
2       True
3       True
4       True
       ...
609     True
610     True
611     True
612     True
613    False
Name: Loan_Status_Y, Length: 614, dtype: bool

In [25]:
!pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scikit-learn in c:\users\jacob\appdata\roaming\python\python313\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\jacob\appdata\roaming\python\python313\site-packages (from scikit-learn) (2.3.2)
Requirement already satisfied: scipy>=1.10.0 in c:\users\jacob\appdata\roaming\python\python313\site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.3.0 in c:\users\jacob\appdata\roaming\python\python313\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\jacob\appdata\roaming\python\python313\site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [26]:
#X  → Inputs / questions

#Y  → Output / answer you want the computer to learn
from sklearn.model_selection import train_test_split
#x_train, y_train	Teach the model
#x_test, y_test	Test the model
#test_size=0.25
#➡ 25% data for testing
#➡ 75% data for training
#random_state=0
#➡ Ensures same split every time
#x_train	Questions the model learns from
#y_train	Correct answers for learning
#x_test	 New questions (exam)
#y_test	  Correct answers (answer key)
#y_test
# Actual / real answers
#(from the dataset)

#y_pred
#Predicted answers
#(from the ML model)

x_train,x_test,y_train,y_test=train_test_split(
    x,y,test_size=0.25,random_state=0
)
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=(0))

from sklearn.linear_model import LogisticRegression
m1=LogisticRegression()
m1.fit(x_train, y_train)
y_pred=m1.predict(x_test)

from sklearn.metrics import accuracy_score,confusion_matrix
acc=accuracy_score(y_test, y_pred)
c=confusion_matrix(y_test,y_pred)
print(acc)
print(c)

ValueError: could not convert string to float: 'LP001138'

In [27]:
#X  → Inputs / questions

#Y  → Output / answer you want the computer to learn
from sklearn.model_selection import train_test_split
#x_train, y_train	Teach the model
#x_test, y_test	Test the model
#test_size=0.25
#➡ 25% data for testing
#➡ 75% data for training
#random_state=0
#➡ Ensures same split every time
#x_train	Questions the model learns from
#y_train	Correct answers for learning
#x_test	 New questions (exam)
#y_test	  Correct answers (answer key)
#y_test
# Actual / real answers
#(from the dataset)

#y_pred
#Predicted answers
#(from the ML model)

x_train,x_test,y_train,y_test=train_test_split(
    x,y,test_size=0.25,random_state=0
)
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=(0))

from sklearn.linear_model import LogisticRegression
m1=LogisticRegression()
m1.fit(x_train, y_train)
y_pred=m1.predict(x_test)

from sklearn.metrics import accuracy_score,confusion_matrix
acc=accuracy_score(y_test, y_pred)
c=confusion_matrix(y_test,y_pred)
print(acc)
print(c)

ValueError: could not convert string to float: 'LP001138'